version: "3.3"
services:
  opensk-devcontainer:
    ports:
      - "1-65535:1-65535"
    build: "."
    tty: true
    privileged: true
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    volumes:
      - /dev/bus/usb:/dev/bus/usb
